View(X4_weeks)
shapiro.test(X4_weeks$weight)
#=====WEIGHT ANALYSIS======#
wt1<-cbind(X4_weeks$weight)
histwt1<-log(X4_weeks$weight)
summary(histwt1)
hist(histwt1) #Logging the 'weight' results normalized the data
kruskal.test(weight ~ treat, data=X4_weeks)
kruskal.test(weight ~ week, data=X4_weeks)
kruskal.test(weight ~ anno, data=X4_weeks)
#===Weight t-test and glm and interaction analysis====#
wtaus<-aov(weight ~ week + anno + treat, data=X4_weeks)
aov(wtaus)
summary(wtaus)
wtaus1<-glm(weight ~ week + anno + treat + week*treat + anno*treat +anno*week, data=X4_weeks)
glm(wtaus1)
summary(wtaus1)
wt<-as.factor(X4_weeks$weight)
levels(wt) #This shows you the numbers that you have in each line
wtaus1<-cbind(X4_weeks, weight=as.factor(X4_weeks$weight))
head(X4_weeks)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.
wtaus1fact<-as.factor(X4_weeks$weight)
levels(wtaus1fact)
trtbywk<-aov(weight ~ week*treat, data=X4_weeks)
summary(trtbywk)
X4_weeks<-cbind(X4_weeks, time=as.factor(X4_weeks$week))
head(X4_weeks)
X4_weeks<-cbind(X4_weeks, brum=as.factor(X4_weeks$treat))
head(X4_weeks)
wtaus2<-glm(weight ~ time*brum, data=X4_weeks)
summary(wtaus2)
wtaus3<-glm(weight~treat + week + anno, data=X4_weeks)
summary(wtaus3)
#=====SUL ANALYSIS======#
sul1<-cbind(X4_weeks$sul)
histsul<-log(X4_weeks$sul)
summary(histsul)
hist(histsul) #Logging the 'weight' results normalized the data
kruskal.test(sul ~ treat, data=X4_weeks)
kruskal.test(sul ~ week, data=X4_weeks)
kruskal.test(sul ~ anno, data=X4_weeks)

#===sul Anova and interaction analysis====#
sulaov<-aov(sul ~ treat, data=X4_weeks)
aov(sulaov)
summary(sulaov)
sulaov1<-aov(sul ~ time + anno + brum, data=X4_weeks)
aov(sulaov1)
summary(sulaov)
sulaus<-aov(sul ~ time + anno + brum + time*brum + anno*brum +anno*time, data=X4_weeks)
aov(sulaus)
summary(sulaus)
sul1<-as.factor(X4_weeks$sul)
levels(sul1) #This shows you the numbers that you have in each line
sulaus1<-cbind(X4_weeks, sul=as.factor(X4_weeks$sul))
head(X4_weeks)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.
sulaus1fact<-as.factor(X4_weeks$sul)
levels(sul1)
trtbywk<-aov(sul ~ week*treat, data=X4_weeks)
summary(trtbywk)
X4_weeks<-cbind(X4_weeks, time=as.factor(X4_weeks$week))
head(X4_weeks)
X4_weeks<-cbind(X4_weeks, brum=as.factor(X4_weeks$treat))
head(X4_weeks)
wtaus2<-glm(sul ~ time*brum, data=X4_weeks)
profile(wtaus2)
#=====SMI ANALYSIS======#
SMI1<-cbind(X4_weeks$SMI)
histSMI<-log(X4_weeks$SMI)
summary(histSMI)
hist(histSMI) #Logging the 'weight' results normalized the data
kruskal.test(SMI ~ treat, data=X4_weeks)
kruskal.test(SMI ~ week, data=X4_weeks)
kruskal.test(SMI ~ anno, data=X4_weeks)

#===sul Anova and interaction analysis 4 WEEKS ====#
SMIaov<-aov(SMI ~ week + anno + treat, data=X4_weeks)
aov(SMIaov)
summary(SMIaov)
SMIaov1<-aov(SMI ~ treat, data=X4_weeks)
aov(SMIaov)
summary(SMIaov1)
SMIaus<-glm(SMI ~ week + anno + treat + treat*week, data=X4_weeks)
glm(SMIaus)
summary(SMIaus)
SMI1<-as.factor(X4_weeks$SMI)
levels(SMI1) #This shows you the numbers that you have in each line
SMIaus1<-cbind(X4_weeks, SMI=as.factor(X4_weeks$SMI))
head(X4_weeks)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.
SMIaus1fact<-as.factor(X4_weeks$SMI)
levels(SMIaus1fact)
trtbywk<-glm(SMI ~ week*treat, data=X4_weeks)
summary(trtbywk)
X4_weeks<-cbind(X4_weeks, time=as.factor(X4_weeks$week))
head(time)
X4_weeks<-cbind(X4_weeks, brum=as.factor(X4_weeks$treat))
head(brum)
SMIaus1<-glm(SMI ~ week*treat, data=X4_weeks)
summary(SMIaus1)
SMIAUS2<-glm(SMI ~ brum + time + brum*time, data=X4_weeks)
summary(SMIAUS2)
#=========SMI week 12=========#
View(X12_week)
SMI1<-cbind(X12_week$smi)
histSMI<-log(X12_week$smi)
summary(histsmi)
hist(histSMI) #Logging the 'weight' results normalized the data
kruskal.test(smi ~ treat, data=X12_week)
kruskal.test(smi ~ week, data=X12_week)
kruskal.test(smi ~ anno, data=X12_weeks)
SMIaov<-aov(smi ~ week + anno + treat, data=X12_week)
aov(SMIaov)
summary(SMIaov)
SMIaov1<-aov(smi ~ treat, data=X12_week)
aov(SMIaov)
summary(SMIaov1)
SMIaus<-aov(smi ~ week + anno + treat + treat*week, data=X12_weeks)
glm(SMIaus)
summary(SMIaus)
SMI1<-as.factor(X12_week$smi)
levels(SMI1) #This shows you the numbers that you have in each line
SMIaus1<-cbind(X12_week, SMI=as.factor(X12_week$smi))
head(X12_week)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.
SMIaus1fact<-as.factor(X12_week$smi)
levels(SMIaus1fact)
trtbywk<-glm(smi ~ week*treat, data=X12_week)
summary(trtbywk)
X12_week<-cbind(X12_week, time=as.factor(X12_week$week))
head(time)
X12_week<-cbind(X12_week, brum=as.factor(X12_week$treat))
head(brum)
SMIAUS2<-glm(smi ~ time*brum, data=X12_week)
summary(smiaus2)
SMIAUS2<-glm(smi ~ brum + time + brum*time, data=X12_week)
summary(SMIAUS2)

View(X12_week)
shapiro.test(X12_week$weight)
#=====WEIGHT ANALYSIS======#
wt1<-cbind(X12_week$weight)
histwt1<-log(X12_week$weight)
summary(histwt1)
hist(histwt1) #Logging the 'weight' results normalized the data
kruskal.test(weight ~ treat, data=X12_week)
kruskal.test(weight ~ week, data=X12_week)
kruskal.test(weight ~ anno, data=X12_week)
#===Weight t-test and glm and interaction analysis====#
wtaus<-aov(weight ~ week + anno + treat, data=X12_week)
aov(wtaus)
summary(wtaus)
wtaus1<-glm(weight ~ week + anno + treat + week*treat + anno*treat +anno*week, data=X12_week)
glm(wtaus1)
summary(wtaus1)
wt<-as.factor(X12_week$weight)
levels(wt) #This shows you the numbers that you have in each line
wtaus1<-cbind(X12_week, weight=as.factor(X12_week$weight))
head(X12_week)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.
wtaus1fact<-as.factor(X12_week$weight)
levels(wtaus1fact)
trtbywk<-glm(weight ~ week*treat, data=X12_week)
summary(trtbywk)
X12_week<-cbind(X12_week, timeweight=as.factor(X12_week$week))
head(X12_week)
X12_week<-cbind(X12_week, annoweight=as.factor(X12_week$treat))
head(X12_week)
X12_week<-cbind(X12_week, brumwt=as.factor(X12_week$brum))
head(X12_week)
smiaus2<-glm(weight ~ timeweight*brumwt + timeweight*annoweight, data=X12_week)
summary(smiaus2)

#========= SUL x12_week ===========#
sul1<-cbind(X12_week$sul)
histsul<-log(X12_week$sul)
summary(histsul)
hist(histsul) #Logging the 'weight' results normalized the data
kruskal.test(sul ~ treat, data=X12_week)
kruskal.test(sul ~ week, data=X12_week)
kruskal.test(sul ~ anno, data=X12_week)

#===sul Anova and interaction analysis====#
View(X12_week)
sulaov1<-aov(sul ~ week + anno + brum, data=X12_week)
aov(sulaov1)
summary(sulaov)
sulaus<-aov(sul ~ week + anno + brum + week*brum + anno*brum +anno*week, data=X12_week)
aov(sulaus)
summary(sulaus)
sul1<-as.factor(X12_week$sul)
levels(sul1) #This shows you the numbers that you have in each line
sulaus1fact<-as.factor(X12_week$sul)
levels(sulaus1fact)#cbind for the data defines each of the numbers and categories that you are trying to analyse and allows you to "slice" the data later as you define what you where you need to analyse the interactions.

X12a<-cbind(X12_week, time=as.factor(X12_week$week))
head(X12a)
X12b<-cbind(X12_week, brum=as.factor(X12_week$treat))
head(X12b)


#===sul Anova and interaction analysis 12 WEEKS ====#

View(X12_week)
sulaov<-aov(sul ~ week + anno + treat, data=X12_week)
aov(sulaov)
summary(sulaov)
sulaus<-glm(sul ~ week + anno + treat + treat*week, data=X12_week)
glm(sulaus)
summary(sulaus)
sulx<-as.factor(X12_week$sul)
levels(sulx) #This shows you the numbers that you have in each line
X12_week<-cbind(X12_week, time=as.factor(X12_week$week))
head(X12_week)
X12_week<-cbind(X12_week, brum=as.factor(X12_week$treat))
head(X12_week)
endsul<-glm(sul ~ brum*time, data=X12_week)
summary(endsul)

